openapi: 3.0.3
info:
  title: Arrosage API
  description: Simple API for controlling the watering system
  version: 1.0.0
  contact:
    name: Arrosage System
  license:
    name: MIT

servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /:
    get:
      summary: Get API information
      description: Root endpoint with API information and available endpoints
      operationId: getApiInfo
      responses:
        '200':
          description: API information
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Arrosage API"
                  version:
                    type: string
                    example: "1.0.0"
                  endpoints:
                    type: object
                    properties:
                      "GET /mode":
                        type: string
                        example: "Get current mode"
                      "POST /mode":
                        type: string
                        example: "Set new mode"
                      "GET /status":
                        type: string
                        example: "Get current sequence status"
                      "POST /pause":
                        type: string
                        example: "Pause the system"
                      "POST /resume":
                        type: string
                        example: "Resume the system"
                      "POST /reset":
                        type: string
                        example: "Reset the system"
                      "GET /settings":
                        type: string
                        example: "Get current settings"
                      "POST /settings":
                        type: string
                        example: "Update settings"

  /mode:
    get:
      summary: Get current mode
      description: Get the current system mode
      operationId: getCurrentMode
      responses:
        '200':
          description: Current mode information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModeResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    
    post:
      summary: Set new mode
      description: Set a new system mode
      operationId: setCurrentMode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModeRequest'
      responses:
        '200':
          description: Mode set successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModeResponse'
        '400':
          description: Invalid mode value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /status:
    get:
      summary: Get current status
      description: Get the current sequence status
      operationId: getCurrentStatus
      responses:
        '200':
          description: Current status information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /pause:
    post:
      summary: Pause system
      description: Pause the watering system
      operationId: pauseSystem
      responses:
        '200':
          description: Pause action result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /resume:
    post:
      summary: Resume system
      description: Resume the watering system from pause
      operationId: resumeSystem
      responses:
        '200':
          description: Resume action result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /reset:
    post:
      summary: Reset system
      description: Reset the watering system to initial state
      operationId: resetSystem
      responses:
        '200':
          description: Reset action result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /settings:
    get:
      summary: Get current settings
      description: Get the current system settings including sequence durations, schedule, and start time
      operationId: getCurrentSettings
      responses:
        '200':
          description: Current settings information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettingsResponse'
        '404':
          description: Settings not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    
    post:
      summary: Update settings
      description: Update the system settings with validation
      operationId: updateSettings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SettingsRequest'
      responses:
        '200':
          description: Settings updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettingsResponse'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ModeRequest:
      type: object
      required:
        - mode
      properties:
        mode:
          type: string
          enum: [manual, auto, semi_auto, pause]
          description: The mode to set
          example: "auto"

    ModeResponse:
      type: object
      required:
        - current
        - valid_modes
      properties:
        current:
          type: string
          enum: [manual, auto, semi_auto, pause]
          description: Current system mode
          example: "auto"
        valid_modes:
          type: array
          items:
            type: string
            enum: [manual, auto, semi_auto, pause]
          description: List of all valid modes
          example: ["manual", "auto", "semi_auto", "pause"]

    StatusResponse:
      type: object
      required:
        - status
        - has_active_sequence
      properties:
        status:
          oneOf:
            - type: "null"
            - $ref: '#/components/schemas/SequenceStatus'
          description: Current sequence status or null if no active sequence
        has_active_sequence:
          type: boolean
          description: Whether there is an active sequence running
          example: true

    SettingsRequest:
      type: object
      required:
        - start_at
        - sequence
        - schedule
      properties:
        start_at:
          type: string
          pattern: "^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$"
          description: Start time in HH:MM format (24-hour)
          example: "20:00"
        sequence:
          type: array
          items:
            type: integer
            minimum: 0
          minItems: 8
          maxItems: 8
          description: Array of 8 duration values in seconds for each relay (0-7)
          example: [3600, 3600, 3600, 3600, 3600, 3600, 3600, 0]
        schedule:
          type: array
          items:
            type: boolean
          minItems: 7
          maxItems: 7
          description: Array of 7 boolean values for each day of the week (Monday=0, Sunday=6)
          example: [false, false, false, false, false, false, true]

    SettingsResponse:
      type: object
      properties:
        start_at:
          type: string
          pattern: "^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$"
          description: Start time in HH:MM format (24-hour)
          example: "20:00"
        sequence:
          type: array
          items:
            type: integer
            minimum: 0
          minItems: 8
          maxItems: 8
          description: Array of 8 duration values in seconds for each relay (0-7)
          example: [3600, 3600, 3600, 3600, 3600, 3600, 3600, 0]
        schedule:
          type: array
          items:
            type: boolean
          minItems: 7
          maxItems: 7
          description: Array of 7 boolean values for each day of the week (Monday=0, Sunday=6)
          example: [false, false, false, false, false, false, true]

    SequenceStatus:
      type: object
      properties:
        opened_relay:
          type: integer
          minimum: 0
          maximum: 7
          description: Currently opened relay number (0-7)
          example: 3
        opened_at:
          type: integer
          description: Unix timestamp when relay was opened
          example: 1758827415
        should_close_at:
          type: integer
          description: Unix timestamp when relay should close
          example: 1758827445

    ActionResponse:
      type: object
      required:
        - success
        - message
        - current_mode
      properties:
        success:
          type: boolean
          description: Whether the action was successful
          example: true
        message:
          type: string
          description: Human-readable message about the action result
          examples:
            - "System paused successfully"
            - "System resumed successfully"
            - "System reset successfully"
        current_mode:
          type: string
          enum: [manual, auto, semi_auto, pause]
          nullable: true
          description: Current system mode after the action
          example: "pause"

    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
          example: "Invalid mode 'invalid'. Valid modes are: ['manual', 'auto', 'semi_auto', 'pause']"

tags:
  - name: Mode
    description: System mode management
  - name: Status
    description: Sequence status information
  - name: Control
    description: System control actions (pause, resume, reset)
